config/routes.rb
Rails.application.routes.draw do
  get 'del/index'
	resources :items do
	resources :orders
	end
  get 'items/index'
  resources :items do
	resources :orders
	end
  root 'items#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :orders, dependent: :destroy
	validates :title, presence: true
	validates :text3, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
	validates :name, presence: true
	validates :number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/del_controller.rb
class DelController < ApplicationController
http_basic_authenticate_with name: "root", password: "root"

	def index
		@items = Item.all
	end
	def show
		@item = Item.find(params[:id])
	end
	def new
		@item = Item.new
	end
	def edit
		@item = Item.find(params[:id])
	end
	def update
		@item = Item.find(params[:id])
 		if @item.update(item_params)
		    redirect_to @item
 		else
 		   render 'edit'
 		end
	end
	def create
		@item = Item.new(item_params)
		if @item.save 
			redirect_to items_path #redirect_to @item
		else
			render 'new'
		end
	end
def destroy
  @item = Item.find(params[:id])
  @item.destroy
 
  redirect_to items_path
end

private
	def item_params
		params.require(:item).permit(:title,:text1,:text2,:text3)
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
	end
	def show
		@item = Item.find(params[:id])
	end
	def new
		@item = Item.new
	end
	def edit
		@item = Item.find(params[:id])
	end
	def update
		@item = Item.find(params[:id])
 		if @item.update(item_params)
		    redirect_to @item
 		else
 		   render 'edit'
 		end
	end
	def create
		@item = Item.new(item_params)
		if @item.save 
			redirect_to items_path #redirect_to @item
		else
			render 'new'
		end
	end
def destroy
  @item = Item.find(params[:id])
  @item.destroy
 
  redirect_to del_index_path
end

private
	def item_params
		params.require(:item).permit(:title,:text1,:text2,:text3)
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
 def index
   @item = Item.find(params[:item_id])

	@orders = Order.all
 end
def show
	@item = Item.find(params[:item_id])
    @order = @item.orders.find(params[:id])
	end
def create
    @item = Item.find(params[:item_id])
    @order = @item.orders.create(order_params)
    redirect_to item_path(@item)
  end
 def destroy
    @item = Item.find(params[:item_id])
    @order = @item.orders.find(params[:id])
    @order.destroy
    redirect_to item_path(@item)
  end

  private
   
    def order_params
      params.require(:order).permit(:name, :address, :number)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/del_helper.rb
module DelHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/del/index.html.erb
<h1><center>Administrator Portal</center></h1>
<br>
<center>

<h1>Items Listed</h1>

<table>
  <tr>
    <th>Item Name</th>
    <th>Item Code</th>
    <th>Restaurant Name</th>
    <th>Price</th>
    <th>Operations</th>
  </tr>
 
  <% @items.each do |item| %>
    <tr>
      <td><%= item.title %></td>
      <td><%= item.text1 %></td>
      <td><%= item.text2 %></td>
      <td><%= item.text3 %></td>
      <td><%= link_to 'Update', edit_item_path(item) %></td>
	<td><%= link_to 'Delete ', item_path(item),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
	<td><%= link_to '  View Orders', item_orders_path(item) %></td>
    </tr>
  <% end %>
</table>
<br><br>
<%= link_to 'Add a new item', new_item_path %>
<br><br><br>
<%= link_to 'Back', items_path %>

</center>

app/views/items/edit.html.erb
<h1>Edit Item Details</h1>
 
<%= form_with(model: @item, local: true) do |form| %>
 
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %> prohibited
        this item from being saved:
      </h2>
      <ul>
          <li>Title cant be blank</li>
	  <li>Price cant be blank</li>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :item_name %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :item_code %><br>
    <%= form.text_area :text1 %>
  </p>
  <p>
    <%= form.label :restaurant_name %><br>
    <%= form.text_area :text2 %>
  </p>
  <p>
    <%= form.label :price %><br>
    <%= form.text_area :text3 %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', del_index_path %>

app/views/items/index.html.erb
<h1><center>Welcome to NITC's Online Food Ordering System</center></h1>
<br>
<center>

<h1>Items Available</h1>

<table>
  <tr>
    <th>Item Name</th>
    <th>Item Code</th>
    <th>Restaurant Name</th>
    <th>Price</th>
    <th></th>
  </tr>
 
  <% @items.each do |item| %>
    <tr>
      <td><%= item.title %></td>
      <td><%= item.text1 %></td>
      <td><%= item.text2 %></td>
      <td><%= item.text3 %></td>
      <td><%= link_to 'Purchase', item_path(item) %></td>
    </tr>
  <% end %>
</table>
<br><br><br>
<%= link_to 'ADMIN LOGIN', del_index_path %>
</center>

app/views/items/new.html.erb
<h1>New Food Item</h1>


<%= form_with scope: :item, url: items_path, local: true do |form| %>
<% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %> prohibited
        this item from being saved:
      </h2>
      <ul>       
          <li>Item name can't be blank</li>
	  <li>Price cannot be blank</li>

      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :item_name %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :item_code %><br>
    <%= form.text_area :text1 %>
  </p>
  <p>
    <%= form.label :restaurant_name %><br>
    <%= form.text_area :text2 %>
  </p>
  <p>
    <%= form.label :price %><br>
    <%= form.text_area :text3 %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<h1>Item Details</h1>
<p>
	<strong>Item Name: </strong>
	<%= @item.title %>
</p>
<p>
	<strong>Item Code: </strong>
	<%= @item.text1 %>
</p>
<p>
	<strong>Restaurant Name: </strong>
	<%= @item.text2 %>
</p>
<p>
	<strong>Price: </strong>
	<%= @item.text3 %>
</p>
<br>
<%= render @item.orders %>
<br><h2> Enter your details to Order</h2>
<%= render 'orders/form' %>


<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: [ @item, @item.orders.build ],cope: :order,local: true) do |form| %>
  <p>
    <%= form.label :customer_name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>
  <p>
    <%= form.label :contact_number %><br>
    <%= form.text_area :number %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/orders/_or.html.erb
 <p>
    <strong>Customer name:</strong>
    <%= @order.name %>
  </p>
 
  <p>
    <strong>Address:</strong>
    <%= @order.address %>
  </p>
  <p>
    <strong>Contact Number:</strong>
    <%= @order.number %>
  </p>
<p>
  <%= link_to 'Delete Order', [order.item, order],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/orders/_order.html.erb
 <p>
    <strong>Customer name:</strong>
    <%= order.name %>
  </p>
 
  <p>
    <strong>Address:</strong>
    <%= order.address %>
  </p>
  <p>
    <strong>Contact Number:</strong>
    <%= order.number %>
  </p>
<p>
  <%= link_to 'Delete Order', [order.item, order],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/orders/index.html.erb
<h2>Orders till date</h2>
<% @item.orders.each do |order| %>
 <p>
    <strong>Customer name:</strong>
    <%= order.name %>
  </p>
 
  <p>
    <strong>Address:</strong>
    <%= order.address %>
  </p>
  <p>
    <strong>Contact Number:</strong>
    <%= order.number %>
  </p>
<p>
  <%= link_to 'Delete Order', [order.item, order],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>
<%= link_to 'Back', del_index_path %>

app/views/orders/show.html.erb
 <p>
    <strong>Customer name:</strong>
    <%= @order.name %>
  </p>
 
  <p>
    <strong>Address:</strong>
    <%= @order.address %>
  </p>
  <p>
    <strong>Contact Number:</strong>
    <%= @order.number %>
  </p>
<p>
  <%= link_to 'Delete Order', [order.item, order],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>